apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-bankemachannel-bankema-peer0
  namespace: bankema-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: joinchannel-peer0-join-bankemachannel-bankema-peer0
  chart:
    git: git@github.com:sivaramkannan/blockchain-automation-framework.git
    ref: bankema-customer-staging
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: bankema-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.bankema-net:7051
      localmspid: bankemaMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://bankema-staging-vault.westeurope.cloudapp.azure.com:8200
      authpath: bankema-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/bankema-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/bankema-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: bankemachannel      
    orderer:
      address: orderer1.ordorg-net:7050

