apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-wsfschannel-investor
  namespace: investor-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-wsfschannel-investor
  chart:
    git: git@github.com:sivaramkannan/blockchain-automation-framework.git
    ref: intainabsdemo
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: investor-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.investor-net:7051
      localmspid: investorMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://159.89.141.74:8200
      authpath: investor-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/investor-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/investor-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: wsfschannel      
    orderer:
      address: orderer1.intain-net:7050
    anchorstx: |-
      CucCChkKFwgCGgYIy8aL/wUiC3dzZnNjaGFubmVsEskCCsYCCgt3c2ZzY2hhbm5lbBJkEmIKC0Fw
      cGxpY2F0aW9uElMIARJPCgtpbnZlc3Rvck1TUBJAGgcKA01TUBIAIgoKBkFkbWlucxIAIg8KC0Vu
      ZG9yc2VtZW50EgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSABrQARLNAQoLQXBwbGljYXRpb24S
      vQEIARK4AQoLaW52ZXN0b3JNU1ASqAEIARpcCgtBbmNob3JQZWVycxJNEkMKQQo8cGVlcjAuaW52
      ZXN0b3ItbmV0LmludmVzdG9yLnN0YWdpbmcuaW50YWluYWJzZGVtby5lbXVseWEuY29tEPtBGgZB
      ZG1pbnMaBwoDTVNQEgAiDwoLRW5kb3JzZW1lbnQSACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIA
      IgoKBkFkbWlucxIAKgZBZG1pbnM=

