apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-org3-betachannel
  namespace: org3-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-org3-betachannel
  chart:
    git: git@github.com:sivaramkannan/blockchain-automation-framework.git
    ref: intainabsdemo
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: org3-net
      network:
        version 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.org3-net:7051
      localmspid: org3MSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://159.89.141.74:8200
      authpath: org3-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/org3-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/org3-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: betachannel
    orderer:
      address: orderer1.ordorg-net:7050
    channeltx: |-
      