apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: peer0-org4-cli
  namespace: org4-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: peer0-org4-cli
  chart:
    git: git@github.com:sivaramkannan/blockchain-automation-framework.git
    ref: intainabsdemo
    path: platforms/hyperledger-fabric/charts/fabric_cli    
  values:
    metadata:
      namespace: org4-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      class: org4sc
      size: 1Gi
    vault:
      role: vault-role
      address: http://159.89.141.74:8200
      authpath: org4-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/org4-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/org4-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    peer:
      name: peer0
      localmspid: org4MSP
      tlsstatus: true
      address: peer0.org4-net:7051
    orderer:
      address: orderer1.ordorg-net:7050
