apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-org1-allchannel
  namespace: org1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-org1-allchannel
  chart:
    git: git@github.com:sivaramkannan/blockchain-automation-framework.git
    ref: intainabsdemo
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: org1-net
      network:
        version 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.org1-net:7051
      localmspid: org1MSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://159.89.141.74:8200
      authpath: org1-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/org1-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/org1-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.ordorg-net:7050
    channeltx: |-
      Cu4DChgKFggCGgYImpex/wUiCmFsbGNoYW5uZWwS0QMKzgMKCmFsbGNoYW5uZWwSVRJDCgtBcHBs
      aWNhdGlvbhI0EgsKB29yZzJNU1ASABILCgdvcmczTVNQEgASCwoHb3JnNE1TUBIAEgsKB29yZzFN
      U1ASABoOCgpDb25zb3J0aXVtEgAa6AISxQIKC0FwcGxpY2F0aW9uErUCCAESCwoHb3JnMk1TUBIA
      EgsKB29yZzNNU1ASABILCgdvcmc0TVNQEgASCwoHb3JnMU1TUBIAGiQKDENhcGFiaWxpdGllcxIU
      EgoKCAoEVjJfMBIAGgZBZG1pbnMiLAoLRW5kb3JzZW1lbnQSHRITCAMSDwoLRW5kb3JzZW1lbnQQ
      AhoGQWRtaW5zIjUKFExpZmVjeWNsZUVuZG9yc2VtZW50Eh0SEwgDEg8KC0VuZG9yc2VtZW50EAIa
      BkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcS
      DQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlu
      cyoGQWRtaW5zGh4KCkNvbnNvcnRpdW0SEBIOCgxNeUNvbnNvcnRpdW0=